name: Deploy to Cluster Services

on:
  release:
    types: [published, released]
    
env:
  IMAGE_NAME: core-website
  REGISTRY: ${{ secrets.PRODUCTION_REGISTRY }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

jobs:
  productionize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: "${{ github.ref }}"
      - name: Build production container
        run: |
          docker build . --tag $IMAGE_NAME:production
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}
      - name: Publish
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          doctl registry login
          docker tag $IMAGE_NAME:production $REGISTRY/$SERVICE_NAME-$IMAGE_NAME:production-$VERSION
          docker push $REGISTRY/$SERVICE_NAME-$IMAGE_NAME:production-$VERSION
