name: Deploy

on:
  push:
    branches:
      - SM-20
#  registry_package:
#    types: [published]

env:
  IMAGE_NAME: core-website
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Pull packages image
        if: github.ref != 'refs/heads/main'
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          docker pull $IMAGE_ID:$VERSION
